# Site settings
title: "Andrew K Moran"
description: "Andrew K. Moran - systems neuroscientist"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Andrew K. Moran"
resume_title:                   ""
resume_header_intro: "<p> Hello! I am a systems neuroscientist interested in olfaction, motor systems, and how sensorimotor integration across brain regions encoding both smell and movement.</p> <p>I am currently a Postdoctoral Fellow working with Diego Restrepo and Abigail Person at the University of Colorado, Anschutz Medical Campus where I am examining how cerebellar circuits compute sensorimotor transforms in odor plume navigation behavior. 

# Decide which sections to use
# comment out to hide
resume_section_experience:      false
resume_section_education:       false
resume_section_projects:        false
resume_section_skills:          false
resume_section_recognition:     false
resume_section_links:           false
resume_section_associations:    false
resume_section_papers:          true
resume_section_posters:         false
resume_section_software:        false
resume_section_teaching:        false
resume_section_talks:           false
resume_section_interests:       false

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  # resume_email:                 "andsinpants@gmail.com"
  resume_github_url:            "https://github.com/andsinpants"
  resume_scholar_url:           "https://scholar.google.com/citations?user=C6OEeQMAAAAJ&hl=en"
  # resume_twitter_url:           ""
# resume_dribbble_url:          ""
  # resume_facebook_url:          ""
  resume_linkedin_url:          "https://www.linkedin.com/in/andrew-k-moran-phd-912848b5/"
  # resume_instagram_url:         ""
  # resume_website_url:           ""
#   resume_medium_url:            ""
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
