# Site settings
title: "Andrew K Moran"
description: "Andrew K Moran - industrial systems neuroscientist"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Andrew K Moran"
resume_title:                   ""
resume_header_intro: "<p><i>I am a Core Director: Where science and tech meets product strategy.</i></p>
<p> My predoc was performed with <a href=\"http://www.wachowiaklab.org/\">Matt Wachowiak</a> at the U.</p>
<p>My postdoc was at CU Anschutz with <a href=\"http://www.restrepolab.org/\">Diego Restrepo</a> and <a href=\"http://www.personlab.org/\">Abigail Person</a>. 
<p>My basic research work and applied experience has broad relevance in the fields of: <ul>
<li>Game/app creation for use in digital health research and education</li>
<li>VR + robotics for treating sensorimotor disease states</li>
<li>brain-computer interfaces</li>
<li>computer science principles in data storage/accessibility</li>
<li>novel pharmaceutical agents to treat brain disease states</li>
<li>perfumery, essential/cannabis oils, and flavor perception</li></ul></p>"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "andrewkmoran.phd@gmail.com"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "no"

# Decide which sections to use
# comment out to hide
resume_section_experience:       true
resume_section_education:        true
resume_section_projects:         true
#resume_section_skills:          false
resume_section_recognitions:     true
#resume_section_links:           false
resume_section_associations:     true
resume_section_papers:           true
resume_section_posters:          true
#resume_section_software:        false
resume_section_teaching:         true
resume_section_talks:            true
resume_section_interests:        true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_email:                "andrewkmoran.phd@gmail.com"
  resume_github_url:            "https://github.com/andsinpants"
  resume_scholar_url:           "https://scholar.google.com/citations?user=C6OEeQMAAAAJ&hl=en"
  # resume_twitter_url:           ""
  # resume_dribbble_url:          ""
  # resume_facebook_url:          ""
  resume_linkedin_url:          "https://www.linkedin.com/in/andrew-k-moran-phd-912848b5/"
  # resume_instagram_url:         ""
  resume_website_url:           "https://www.andrewkmoran.com/"
  # resume_medium_url:            "https://medium.com/@andsinpants"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
